version: '3.8'

services:
  internal-service:
    image: nginx:alpine
    container_name: internal-service
    volumes:
      - ./services/internal-html:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: unless-stopped

  external-service:
    image: nginx:alpine
    container_name: external-service
    volumes:
      - ./services/external-html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
